//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkOnline.Pages {
    
    
    public partial class LinkCloud {
        
        /// <summary>
        /// lblPageTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Label lblPageTitle;
        
        /// <summary>
        /// lblBeta control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Label lblBeta;
        
        /// <summary>
        /// pnlExplorer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlExplorer;
        
        /// <summary>
        /// pnlExplorerNavigation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlExplorerNavigation;
        
        /// <summary>
        /// txtSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.TextBox txtSearch;
        
        /// <summary>
        /// pnlGridViewHeadlineItemCreationDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlGridViewHeadlineItemCreationDate;
        
        /// <summary>
        /// lblGridViewHeadlineCreationDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Label lblGridViewHeadlineCreationDate;
        
        /// <summary>
        /// pnlGridViewHeadlineItemModificationDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlGridViewHeadlineItemModificationDate;
        
        /// <summary>
        /// lblGridViewHeadlineModificationDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Label lblGridViewHeadlineModificationDate;
        
        /// <summary>
        /// pnlGridViewHeadlineItemSize control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlGridViewHeadlineItemSize;
        
        /// <summary>
        /// lblGridViewHeadlineSize control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Label lblGridViewHeadlineSize;
        
        /// <summary>
        /// pnlGridViewHeadlineItemType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlGridViewHeadlineItemType;
        
        /// <summary>
        /// lblGridViewHeadlineType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Label lblGridViewHeadlineType;
        
        /// <summary>
        /// pnlGridViewHeadlineItemAuthor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlGridViewHeadlineItemAuthor;
        
        /// <summary>
        /// lblGridViewHeadlineAuthor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Label lblGridViewHeadlineAuthor;
        
        /// <summary>
        /// lblGridViewHeadlineName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Label lblGridViewHeadlineName;
        
        /// <summary>
        /// pnlFiles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlFiles;
        
        /// <summary>
        /// boxChooseNewAction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Box boxChooseNewAction;
        
        /// <summary>
        /// btnUpload control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton btnUpload;
        
        /// <summary>
        /// btnCreateDirectory control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton btnCreateDirectory;
        
        /// <summary>
        /// lblUpload control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Label lblUpload;
        
        /// <summary>
        /// lblCreateDirectory control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Label lblCreateDirectory;
        
        /// <summary>
        /// boxUploadFile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Box boxUploadFile;
        
        /// <summary>
        /// fuUploadFile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FileUpload fuUploadFile;
        
        /// <summary>
        /// btnUploadFileConfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Button btnUploadFileConfirm;
        
        /// <summary>
        /// btnUploadFileCancel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Button btnUploadFileCancel;
        
        /// <summary>
        /// boxCreateDirectory control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Box boxCreateDirectory;
        
        /// <summary>
        /// lblCreateDirectoryName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Label lblCreateDirectoryName;
        
        /// <summary>
        /// txtCreateDirectoryName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.TextBox txtCreateDirectoryName;
        
        /// <summary>
        /// btnCreateDirectoryConfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Button btnCreateDirectoryConfirm;
        
        /// <summary>
        /// btnCreateDirectoryCancel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Button btnCreateDirectoryCancel;
        
        /// <summary>
        /// boxCreateFolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Box boxCreateFolder;
        
        /// <summary>
        /// lblCreateFolderName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Label lblCreateFolderName;
        
        /// <summary>
        /// txtCreateFolderName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.TextBox txtCreateFolderName;
        
        /// <summary>
        /// btnCreateFolderConfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Button btnCreateFolderConfirm;
        
        /// <summary>
        /// btnCreateFolderCancel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Button btnCreateFolderCancel;
        
        /// <summary>
        /// box1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Box box1;
        
        /// <summary>
        /// TreeView1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TreeView TreeView1;
        
        /// <summary>
        /// ImageMove control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Button ImageMove;
        
        /// <summary>
        /// Button1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Button Button1;
        
        /// <summary>
        /// hdfLibraryViewState control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText hdfLibraryViewState;
        
        /// <summary>
        /// ConnectPowerBI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinkOnline.Classes.Controls.ConnectPowerBI ConnectPowerBI;
    }
}
