USE [master]

CREATE DATABASE [###CLIENTNAME###]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'###CLIENTNAME###', FILENAME = N'###DATABASEROOT###\###CLIENTNAME###.mdf', MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'###CLIENTNAME###_log', FILENAME = N'###DATABASEROOT###\###CLIENTNAME###_log.ldf' , MAXSIZE = 2048GB , FILEGROWTH = 10%)
ALTER DATABASE [###CLIENTNAME###] SET COMPATIBILITY_LEVEL = 120


ALTER DATABASE [###CLIENTNAME###] SET RECOVERY SIMPLE ;