//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkOnline.Classes.Controls {
    
    
    public partial class ConnectPowerBI {
        
        /// <summary>
        /// lblConnectPowerBIDescriptionTarget control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Label lblConnectPowerBIDescriptionTarget;
        
        /// <summary>
        /// lblConnectPowerBITargetPowerBI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Label lblConnectPowerBITargetPowerBI;
        
        /// <summary>
        /// lblConnectPowerBITargetTableau control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Label lblConnectPowerBITargetTableau;
        
        /// <summary>
        /// lblConnectPowerBITargetTable control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Label lblConnectPowerBITargetTable;
        
        /// <summary>
        /// lblConnectPowerBIDescriptionSave control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Label lblConnectPowerBIDescriptionSave;
        
        /// <summary>
        /// lblConnectPowerBISaveName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Label lblConnectPowerBISaveName;
        
        /// <summary>
        /// txtConnectPowerBISaveName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.TextBox txtConnectPowerBISaveName;
        
        /// <summary>
        /// lnkConnectPowerBISaveConfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.LinkButton lnkConnectPowerBISaveConfirm;
        
        /// <summary>
        /// lnkConnectPowerBISaveCancel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.LinkButton lnkConnectPowerBISaveCancel;
        
        /// <summary>
        /// lblConnectPowerBIDescription1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Label lblConnectPowerBIDescription1;
        
        /// <summary>
        /// lblConnectPowerBIPassword control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Label lblConnectPowerBIPassword;
        
        /// <summary>
        /// txtConnectPowerBIPassword control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.TextBox txtConnectPowerBIPassword;
        
        /// <summary>
        /// lnkConnectPowerBIConfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.LinkButton lnkConnectPowerBIConfirm;
        
        /// <summary>
        /// lnkConnectPowerBICancel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.LinkButton lnkConnectPowerBICancel;
        
        /// <summary>
        /// lblConnectPowerBIDescription2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Label lblConnectPowerBIDescription2;
        
        /// <summary>
        /// lblConnectPowerBIDescription3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtilities.Controls.Label lblConnectPowerBIDescription3;
    }
}
